parameters:
    bdifttt.controller.class: BD\Bundle\IFTTTBundle\Controller\IFTTT
    bdifttt.ifttt.request_parser.class: BD\Bundle\IFTTTBundle\IFTTT\RequestParser
    bdifttt.factory.class: BD\Bundle\IFTTTBundle\DependencyInjection\Factory

services:
    bdifttt.controller:
        class: %bdifttt.controller.class%
        arguments:
            - @bdifttt.ifttt.request_parser
            - @bdifttt.handler
        calls:
            - [ setContainer, [ @service_container ] ]

    bdifttt.ifttt.request_parser:
        class: %bdifttt.ifttt.request_parser.class%
